{
  "openapi": "3.0.0",
  "info": {
    "title": "API de Logs e Usuários",
    "version": "1.0.0",
    "description": "API para gerenciamento de logs e usuários com autenticação via Bearer Token."
  },
  "servers": [
    {
      "url": "http://localhost:3333/api",
      "description": "Local"
    },
    {
      "url": "https://api.pscodium.dev/api",
      "description": "Prod"
    }
  ],
  "tags": [
    {
      "name": "logs",
      "description": "Logs Requests"
    },
    {
      "name": "users",
      "description": "Users Requests"
    },
    {
      "name": "permissions",
      "description": "User Permissions"
    },
    {
      "name": "storage",
      "description": "User File Storage"
    }
  ],
  "paths": {
    "/logs/get": {
      "get": {
        "tags": [
          "logs"
        ],
        "summary": "Obter logs",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Logs obtidos com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LogSchema"
                }
              }
            }
          },
          "404": {
            "description": "[REQUEST ERROR] - Error trying get logs"
          },
          "5XX": {
            "description": "[REQUEST ERROR] - Bad Request"
          }
        }
      }
    },
    "/logs/get/format": {
      "get": {
        "tags": [
          "logs"
        ],
        "summary": "Obter logs formatados",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Logs formatados obtidos com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LogSchema"
                }
              }
            }
          },
          "404": {
            "description": "[REQUEST ERROR] - Error trying get logs"
          },
          "5XX": {
            "description": "[REQUEST ERROR] - Bad Request"
          }
        }
      }
    },
    "/register": {
      "post": {
        "tags": [
          "users"
        ],
        "summary": "Registrar um novo usuário",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  },
                  "nickname": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string",
                    "format": "email"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Usuário registrado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegisterResponseSchema"
                }
              }
            }
          },
          "400": {
            "description": "Erro interno do servidor",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "stack": {
                      "type": "string",
                      "default": "[ERROR](400) - Invalid password pattern."
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "Erro interno do servidor",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "stack": {
                      "type": "string",
                      "default": "[ERROR](409) - User already exists."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno do servidor",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "stack": {
                      "type": "string",
                      "default": "[REQUEST ERROR] - Bad Request"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "tags": [
          "users"
        ],
        "summary": "Login do usuário",
        "description": "Faz login e retorna um token JWT. O tipo de login pode ser alterado com o parâmetro `type`.",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "login": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Login realizado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CheckAuthResponseSchema"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](401) - You need to provides a authorization token."
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](403) - You don't have permissions for use this route."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno do servidor",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "stack": {
                      "type": "string",
                      "default": "[REQUEST ERROR] - Bad Request"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/check/auth": {
      "get": {
        "tags": [
          "users"
        ],
        "summary": "Verificar autenticação do usuário",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Usuário autenticado",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CheckAuthResponseSchema"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](401) - You need to provides a authorization token."
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](403) - You don't have permissions for use this route."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno do servidor",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "stack": {
                      "type": "string",
                      "default": "[AUTHORIZATION REQUEST ERROR] - Bad Request"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/logout": {
      "get": {
        "tags": [
          "users"
        ],
        "summary": "Logout do usuário",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Logout realizado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "Unexpected error on delete session."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno do servidor",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "stack": {
                      "type": "string",
                      "default": "[AUTHORIZATION REQUEST ERROR] - Bad Request"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/data/user": {
      "get": {
        "tags": [
          "users"
        ],
        "summary": "Obter dados do usuário",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Dados do usuário obtidos com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CheckAuthResponseSchema"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](401) - You need to provides a authorization token."
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](403) - You don't have permissions for use this route."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno do servidor",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "stack": {
                      "type": "string",
                      "default": "[AUTHORIZATION REQUEST ERROR] - Bad Request"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users": {
      "get": {
        "tags": [
          "users"
        ],
        "summary": "Obter todos os usuários",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Lista de usuários obtida com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "oneOf": [
                      {
                        "$ref": "#/components/schemas/UsersResponseSchema"
                      },
                      {
                        "$ref": "#/components/schemas/UsersResponseSchema"
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](401) - You need to provides a authorization token."
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](403) - You don't have permissions for use this route."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno do servidor",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "stack": {
                      "type": "string",
                      "default": "[AUTHORIZATION REQUEST ERROR] - Bad Request"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/{id}": {
      "get": {
        "tags": [
          "users"
        ],
        "summary": "Obter um usuário específico",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "ID do usuário",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Usuário obtido com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponseSchema"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](401) - You need to provides a authorization token."
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](403) - You don't have permissions for use this route."
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](404) - User does not exist (Invalid ID)."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno do servidor",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "stack": {
                      "type": "string",
                      "default": "[AUTHORIZATION REQUEST ERROR] - Bad Request"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "users"
        ],
        "summary": "Deletar um usuário específico",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "ID do usuário",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Usuário obtido com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "default": true
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[REQUEST ERROR] - Missing required route parameter 'id'"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](401) - You need to provides a authorization token."
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](403) - You don't have permissions for use this route."
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](404) - The user you are trying to delete does not exist."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno do servidor",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "stack": {
                      "type": "string",
                      "default": "[AUTHORIZATION REQUEST ERROR] - Bad Request"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/update": {
      "put": {
        "tags": [
          "users"
        ],
        "summary": "Update user",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserUpdateResponseSchema"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "As permissões do usuário foram alteradas com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "success": {
                      "type": "boolean"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "Invalid data"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](401) - You need to provides a authorization token."
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](403) - You don't have permissions for use this route."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno do servidor",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "stack": {
                      "type": "string",
                      "default": "[AUTHORIZATION REQUEST ERROR] - Bad Request"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/{id}/update/perms": {
      "put": {
        "tags": [
          "permissions"
        ],
        "summary": "Update user permissions",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PermissionSchema"
              }
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "ID do usuário",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "As permissões do usuário foram alteradas com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "success": {
                      "type": "boolean"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "examples": {
                  "missingId": {
                    "summary": "Missing ID parameter",
                    "value": {
                      "message": "[REQUEST ERROR] - Missing required route parameter 'id'"
                    }
                  },
                  "invalidData": {
                    "summary": "Invalid data",
                    "value": {
                      "message": "Invalid data"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](401) - You need to provides a authorization token."
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](403) - You don't have permissions for use this route."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno do servidor",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "stack": {
                      "type": "string",
                      "default": "[AUTHORIZATION REQUEST ERROR] - Bad Request"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/storage/upload/{folderId}": {
      "post": {
        "tags": [
          "storage"
        ],
        "summary": "Upload File",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "folderId",
            "in": "path",
            "required": true,
            "description": "ID do usuário",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "media": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "File successfully uploaded",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/StorageFileUploadResponseSchema"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "examples": {
                  "missingId": {
                    "summary": "Missing Folder ID parameter",
                    "value": {
                      "message": "[REQUEST ERROR] - Missing required route parameter 'folderId'"
                    }
                  },
                  "invalidData": {
                    "summary": "Invalid data",
                    "value": {
                      "message": "Invalid data"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](401) - You need to provides a authorization token."
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](403) - You don't have permissions for use this route."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno do servidor",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "stack": {
                      "type": "string",
                      "default": "[AUTHORIZATION REQUEST ERROR] - Bad Request"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/storage/folders/create": {
      "post": {
        "tags": [
          "storage"
        ],
        "summary": "Create Folder",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "folderName": {
                    "type": "string"
                  },
                  "type": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Folder successfully created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/StorageFolderCreateResponseSchema"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "examples": {
                  "invalidData": {
                    "summary": "Invalid data",
                    "value": {
                      "message": "Invalid data"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](401) - You need to provides a authorization token."
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](403) - You don't have permissions for use this route."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno do servidor",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "stack": {
                      "type": "string",
                      "default": "[AUTHORIZATION REQUEST ERROR] - Bad Request"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/storage/files": {
      "get": {
        "tags": [
          "storage"
        ],
        "summary": "Get Files",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Files successfully returned",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "oneOf": [
                      {
                        "$ref": "#/components/schemas/FilesResponseSchema"
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "examples": {
                  "invalidData": {
                    "summary": "Invalid data",
                    "value": {
                      "message": "Invalid data"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](401) - You need to provides a authorization token."
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](403) - You don't have permissions for use this route."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno do servidor",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "stack": {
                      "type": "string",
                      "default": "[AUTHORIZATION REQUEST ERROR] - Bad Request"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/storage/folders": {
      "get": {
        "tags": [
          "storage"
        ],
        "summary": "Get Folders",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Folders successfully returned",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "oneOf": [
                      {
                        "$ref": "#/components/schemas/FoldersResponseSchema"
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "examples": {
                  "invalidData": {
                    "summary": "Invalid data",
                    "value": {
                      "message": "Invalid data"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](401) - You need to provides a authorization token."
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](403) - You don't have permissions for use this route."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno do servidor",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "stack": {
                      "type": "string",
                      "default": "[AUTHORIZATION REQUEST ERROR] - Bad Request"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/storage/delete/{id}/folder/{folderId}": {
      "delete": {
        "tags": [
          "storage"
        ],
        "summary": "Delete File",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "File ID",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "folderId",
            "in": "path",
            "required": true,
            "description": "Folder ID",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "File successfully deleted",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "default": true
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[REQUEST ERROR] - Missing required route parameter 'id' or 'folderId'"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](401) - You need to provides a authorization token."
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](403) - You don't have permissions for use this route."
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](404) - The user you are trying to delete does not exist."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno do servidor",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "stack": {
                      "type": "string",
                      "default": "[AUTHORIZATION REQUEST ERROR] - Bad Request"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/storage/folders/delete/{id}": {
      "delete": {
        "tags": [
          "storage"
        ],
        "summary": "Delete Folder",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "Folder Id",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Folder successfully deleted",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "default": true
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[REQUEST ERROR] - Missing required route parameter 'id' or 'folderId'"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](401) - You need to provides a authorization token."
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](403) - You don't have permissions for use this route."
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "default": "[ERROR](404) - The user you are trying to delete does not exist."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno do servidor",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "stack": {
                      "type": "string",
                      "default": "[AUTHORIZATION REQUEST ERROR] - Bad Request"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "LogSchema": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "_index": {
            "type": "string",
            "default": "logs"
          },
          "_score": {
            "type": "integer",
            "default": null
          },
          "message": {
            "type": "string"
          },
          "timestamp": {
            "type": "string",
            "default": "0000-000-00T00:00:00.000Z"
          },
          "sort": {
            "type": "array",
            "items": {
              "type": "integer"
            }
          }
        }
      },
      "UserSchema": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "profileIcon": {
            "type": "string"
          },
          "nickname": {
            "type": "string"
          },
          "externalId": {
            "type": "string",
            "description": "External ID for firebase"
          },
          "role": {
            "type": "string",
            "enum": [
              "default",
              "customer",
              "owner",
              "developer",
              "admin"
            ]
          },
          "status": {
            "type": "string",
            "enum": [
              "active",
              "inactive",
              "offline"
            ]
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "verifiedEmail": {
            "type": "boolean"
          },
          "password": {
            "type": "string",
            "writeOnly": true
          },
          "token": {
            "type": "string"
          }
        }
      },
      "PermissionSchema": {
        "type": "object",
        "properties": {
          "master_admin_level": {
            "type": "boolean",
            "default": false
          },
          "can_manage_roles": {
            "type": "boolean",
            "default": false
          },
          "can_generate_apikey": {
            "type": "boolean",
            "default": false
          },
          "can_access_private_routes": {
            "type": "boolean",
            "default": false
          },
          "can_access_admin_routes": {
            "type": "boolean",
            "default": false
          },
          "can_post_article": {
            "type": "boolean",
            "default": false
          }
        }
      },
      "FileSchema": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "UserId": {
            "type": "string"
          },
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          }
        }
      },
      "FolderSchema": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "hex": {
            "type": "string"
          },
          "UserId": {
            "type": "string"
          },
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          }
        }
      },
      "RegisterResponseSchema": {
        "allOf": [
          {
            "$ref": "#/components/schemas/UserSchema"
          },
          {
            "type": "object",
            "properties": {
              "token": {
                "writeOnly": true
              }
            },
            "additionalProperties": false
          }
        ]
      },
      "CheckAuthResponseSchema": {
        "allOf": [
          {
            "$ref": "#/components/schemas/UserSchema"
          },
          {
            "type": "object",
            "properties": {
              "password": {},
              "Permission": {
                "allOf": [
                  {
                    "type": "object"
                  },
                  {
                    "$ref": "#/components/schemas/PermissionSchema"
                  }
                ]
              }
            },
            "additionalProperties": false
          }
        ]
      },
      "UsersResponseSchema": {
        "allOf": [
          {
            "$ref": "#/components/schemas/UserSchema"
          },
          {
            "type": "object",
            "properties": {
              "password": {},
              "token": {
                "writeOnly": true
              }
            },
            "additionalProperties": false
          }
        ]
      },
      "UserResponseSchema": {
        "allOf": [
          {
            "$ref": "#/components/schemas/UsersResponseSchema"
          },
          {
            "type": "object",
            "properties": {
              "Permission": {
                "allOf": [
                  {
                    "type": "object"
                  },
                  {
                    "$ref": "#/components/schemas/PermissionSchema"
                  }
                ]
              }
            }
          }
        ]
      },
      "UserUpdateResponseSchema": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "nickname": {
            "type": "string"
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "profileIcon": {
            "type": "string"
          }
        }
      },
      "StorageFileUploadResponseSchema": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "UserId": {
            "type": "string"
          },
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          }
        }
      },
      "StorageFolderCreateResponseSchema": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "hex": {
            "type": "string"
          },
          "UserId": {
            "type": "string"
          },
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          }
        }
      },
      "FilesResponseSchema": {
        "allOf": [
          {
            "$ref": "#/components/schemas/FileSchema"
          },
          {
            "type": "object",
            "properties": {
              "Folder": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/FolderSchema"
                  }
                ]
              }
            },
            "additionalProperties": false
          }
        ]
      },
      "FoldersResponseSchema": {
        "allOf": [
          {
            "$ref": "#/components/schemas/FolderSchema"
          },
          {
            "type": "object",
            "properties": {
              "filesCount": {
                "type": "integer"
              },
              "File": {
                "allOf": [
                  {
                    "type": "array",
                    "items": {
                      "oneOf": [
                        {
                          "$ref": "#/components/schemas/FileSchema"
                        }
                      ]
                    }
                  }
                ]
              }
            },
            "additionalProperties": false
          }
        ]
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "description": "Token de autenticação Bearer com 36 caracteres."
      }
    }
  }
}